# Generated by Django 4.0.4 on 2022-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=8, verbose_name='发送者')),
                ('me', models.CharField(max_length=8, verbose_name='接收者')),
                ('to', models.TextField(blank=True, null=True, verbose_name='发送列表')),
                ('cc', models.TextField(blank=True, null=True, verbose_name='抄送列表')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_push', models.BooleanField(default=False, verbose_name='已推')),
                ('title', models.CharField(max_length=256, verbose_name='主题')),
                ('content', models.TextField(verbose_name='正文')),
                ('attachments', models.TextField(blank=True, null=True, verbose_name='附件')),
                ('label', models.CharField(blank=True, max_length=16, null=True, verbose_name='标签')),
                ('rdt', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('edt', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '00.消息',
            },
        ),
    ]
